// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajbjlbpoztifqujtiqvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYmpsYnBvenRpZnF1anRpcXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODgzODEsImV4cCI6MjA3MDQ2NDM4MX0.-ZoCI86La6SGeEQ6x0o7twA5onQtXqMYdVFTMj0sqfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});